// <auto-generated />
using System;
using CinemaLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CinemaLibrary.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220119171201_SecondFinalMigration")]
    partial class SecondFinalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CinemaHallTime", b =>
                {
                    b.Property<int>("HallsHallNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeanceTimesID")
                        .HasColumnType("integer");

                    b.HasKey("HallsHallNumber", "SeanceTimesID");

                    b.HasIndex("SeanceTimesID");

                    b.ToTable("CinemaHallTime");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.CinemaHall", b =>
                {
                    b.Property<int>("HallNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("HallName")
                        .HasColumnType("text");

                    b.HasKey("HallNumber");

                    b.ToTable("CinemaHall");

                    b.HasData(
                        new
                        {
                            HallNumber = 1,
                            HallName = "Зал 1"
                        },
                        new
                        {
                            HallNumber = 2,
                            HallName = "Зал 2"
                        },
                        new
                        {
                            HallNumber = 3,
                            HallName = "Зал 3"
                        },
                        new
                        {
                            HallNumber = 4,
                            HallName = "Зал 4"
                        },
                        new
                        {
                            HallNumber = 5,
                            HallName = "Зал 5"
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("ID");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateFinish")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Restriction")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Title = "Боевик"
                        },
                        new
                        {
                            ID = 2,
                            Title = "Ужасы"
                        },
                        new
                        {
                            ID = 3,
                            Title = "Мультфильм"
                        },
                        new
                        {
                            ID = 4,
                            Title = "Комедия"
                        },
                        new
                        {
                            ID = 5,
                            Title = "Фантастика"
                        },
                        new
                        {
                            ID = 6,
                            Title = "Фэнтези"
                        },
                        new
                        {
                            ID = 7,
                            Title = "Драма"
                        },
                        new
                        {
                            ID = 8,
                            Title = "Мелодрама"
                        },
                        new
                        {
                            ID = 9,
                            Title = "Вестерн"
                        },
                        new
                        {
                            ID = 10,
                            Title = "Аниме"
                        },
                        new
                        {
                            ID = 11,
                            Title = "Триллер"
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.HallRow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CinemaHallID")
                        .HasColumnType("integer");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CinemaHallID");

                    b.ToTable("HallRow");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CinemaHallID = 1,
                            RowNumber = 1
                        },
                        new
                        {
                            ID = 2,
                            CinemaHallID = 1,
                            RowNumber = 2
                        },
                        new
                        {
                            ID = 3,
                            CinemaHallID = 1,
                            RowNumber = 3
                        },
                        new
                        {
                            ID = 4,
                            CinemaHallID = 1,
                            RowNumber = 4
                        },
                        new
                        {
                            ID = 5,
                            CinemaHallID = 1,
                            RowNumber = 5
                        },
                        new
                        {
                            ID = 6,
                            CinemaHallID = 1,
                            RowNumber = 6
                        },
                        new
                        {
                            ID = 7,
                            CinemaHallID = 2,
                            RowNumber = 1
                        },
                        new
                        {
                            ID = 8,
                            CinemaHallID = 2,
                            RowNumber = 2
                        },
                        new
                        {
                            ID = 9,
                            CinemaHallID = 2,
                            RowNumber = 3
                        },
                        new
                        {
                            ID = 10,
                            CinemaHallID = 2,
                            RowNumber = 4
                        },
                        new
                        {
                            ID = 11,
                            CinemaHallID = 2,
                            RowNumber = 5
                        },
                        new
                        {
                            ID = 12,
                            CinemaHallID = 2,
                            RowNumber = 6
                        },
                        new
                        {
                            ID = 13,
                            CinemaHallID = 3,
                            RowNumber = 1
                        },
                        new
                        {
                            ID = 14,
                            CinemaHallID = 3,
                            RowNumber = 2
                        },
                        new
                        {
                            ID = 15,
                            CinemaHallID = 3,
                            RowNumber = 3
                        },
                        new
                        {
                            ID = 16,
                            CinemaHallID = 3,
                            RowNumber = 4
                        },
                        new
                        {
                            ID = 17,
                            CinemaHallID = 3,
                            RowNumber = 5
                        },
                        new
                        {
                            ID = 18,
                            CinemaHallID = 3,
                            RowNumber = 6
                        },
                        new
                        {
                            ID = 19,
                            CinemaHallID = 4,
                            RowNumber = 1
                        },
                        new
                        {
                            ID = 20,
                            CinemaHallID = 4,
                            RowNumber = 2
                        },
                        new
                        {
                            ID = 21,
                            CinemaHallID = 4,
                            RowNumber = 3
                        },
                        new
                        {
                            ID = 22,
                            CinemaHallID = 4,
                            RowNumber = 4
                        },
                        new
                        {
                            ID = 23,
                            CinemaHallID = 4,
                            RowNumber = 5
                        },
                        new
                        {
                            ID = 24,
                            CinemaHallID = 4,
                            RowNumber = 6
                        },
                        new
                        {
                            ID = 25,
                            CinemaHallID = 5,
                            RowNumber = 1
                        },
                        new
                        {
                            ID = 26,
                            CinemaHallID = 5,
                            RowNumber = 2
                        },
                        new
                        {
                            ID = 27,
                            CinemaHallID = 5,
                            RowNumber = 3
                        },
                        new
                        {
                            ID = 28,
                            CinemaHallID = 5,
                            RowNumber = 4
                        },
                        new
                        {
                            ID = 29,
                            CinemaHallID = 5,
                            RowNumber = 5
                        },
                        new
                        {
                            ID = 30,
                            CinemaHallID = 5,
                            RowNumber = 6
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.HallSeat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("HallRowID")
                        .HasColumnType("integer");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("HallRowID");

                    b.ToTable("HallSeat");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HallRowID = 1,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 2,
                            HallRowID = 1,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 3,
                            HallRowID = 1,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 4,
                            HallRowID = 1,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 5,
                            HallRowID = 1,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 6,
                            HallRowID = 1,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 7,
                            HallRowID = 1,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 8,
                            HallRowID = 1,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 9,
                            HallRowID = 1,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 10,
                            HallRowID = 1,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 11,
                            HallRowID = 2,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 12,
                            HallRowID = 2,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 13,
                            HallRowID = 2,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 14,
                            HallRowID = 2,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 15,
                            HallRowID = 2,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 16,
                            HallRowID = 2,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 17,
                            HallRowID = 2,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 18,
                            HallRowID = 2,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 19,
                            HallRowID = 2,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 20,
                            HallRowID = 2,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 21,
                            HallRowID = 3,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 22,
                            HallRowID = 3,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 23,
                            HallRowID = 3,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 24,
                            HallRowID = 3,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 25,
                            HallRowID = 3,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 26,
                            HallRowID = 3,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 27,
                            HallRowID = 3,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 28,
                            HallRowID = 3,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 29,
                            HallRowID = 3,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 30,
                            HallRowID = 3,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 31,
                            HallRowID = 4,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 32,
                            HallRowID = 4,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 33,
                            HallRowID = 4,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 34,
                            HallRowID = 4,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 35,
                            HallRowID = 4,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 36,
                            HallRowID = 4,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 37,
                            HallRowID = 4,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 38,
                            HallRowID = 4,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 39,
                            HallRowID = 4,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 40,
                            HallRowID = 4,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 41,
                            HallRowID = 5,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 42,
                            HallRowID = 5,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 43,
                            HallRowID = 5,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 44,
                            HallRowID = 5,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 45,
                            HallRowID = 5,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 46,
                            HallRowID = 5,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 47,
                            HallRowID = 5,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 48,
                            HallRowID = 5,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 49,
                            HallRowID = 5,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 50,
                            HallRowID = 5,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 51,
                            HallRowID = 6,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 52,
                            HallRowID = 6,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 53,
                            HallRowID = 6,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 54,
                            HallRowID = 6,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 55,
                            HallRowID = 6,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 56,
                            HallRowID = 6,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 57,
                            HallRowID = 6,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 58,
                            HallRowID = 6,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 59,
                            HallRowID = 6,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 60,
                            HallRowID = 6,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 61,
                            HallRowID = 7,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 62,
                            HallRowID = 7,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 63,
                            HallRowID = 7,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 64,
                            HallRowID = 7,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 65,
                            HallRowID = 7,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 66,
                            HallRowID = 7,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 67,
                            HallRowID = 7,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 68,
                            HallRowID = 7,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 69,
                            HallRowID = 8,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 70,
                            HallRowID = 8,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 71,
                            HallRowID = 8,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 72,
                            HallRowID = 8,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 73,
                            HallRowID = 8,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 74,
                            HallRowID = 8,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 75,
                            HallRowID = 8,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 76,
                            HallRowID = 8,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 77,
                            HallRowID = 8,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 78,
                            HallRowID = 8,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 79,
                            HallRowID = 9,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 80,
                            HallRowID = 9,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 81,
                            HallRowID = 9,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 82,
                            HallRowID = 9,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 83,
                            HallRowID = 9,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 84,
                            HallRowID = 9,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 85,
                            HallRowID = 9,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 86,
                            HallRowID = 9,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 87,
                            HallRowID = 10,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 88,
                            HallRowID = 10,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 89,
                            HallRowID = 10,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 90,
                            HallRowID = 10,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 91,
                            HallRowID = 10,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 92,
                            HallRowID = 10,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 93,
                            HallRowID = 10,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 94,
                            HallRowID = 10,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 95,
                            HallRowID = 10,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 96,
                            HallRowID = 10,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 97,
                            HallRowID = 11,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 98,
                            HallRowID = 11,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 99,
                            HallRowID = 11,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 100,
                            HallRowID = 11,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 101,
                            HallRowID = 11,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 102,
                            HallRowID = 11,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 103,
                            HallRowID = 11,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 104,
                            HallRowID = 11,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 105,
                            HallRowID = 12,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 106,
                            HallRowID = 12,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 107,
                            HallRowID = 12,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 108,
                            HallRowID = 12,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 109,
                            HallRowID = 12,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 110,
                            HallRowID = 12,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 111,
                            HallRowID = 12,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 112,
                            HallRowID = 12,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 113,
                            HallRowID = 12,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 114,
                            HallRowID = 12,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 115,
                            HallRowID = 13,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 116,
                            HallRowID = 13,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 117,
                            HallRowID = 13,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 118,
                            HallRowID = 13,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 119,
                            HallRowID = 13,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 120,
                            HallRowID = 13,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 121,
                            HallRowID = 13,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 122,
                            HallRowID = 13,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 123,
                            HallRowID = 13,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 124,
                            HallRowID = 14,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 125,
                            HallRowID = 14,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 126,
                            HallRowID = 14,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 127,
                            HallRowID = 14,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 128,
                            HallRowID = 14,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 129,
                            HallRowID = 14,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 130,
                            HallRowID = 14,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 131,
                            HallRowID = 14,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 132,
                            HallRowID = 14,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 133,
                            HallRowID = 14,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 134,
                            HallRowID = 15,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 135,
                            HallRowID = 15,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 136,
                            HallRowID = 15,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 137,
                            HallRowID = 15,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 138,
                            HallRowID = 15,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 139,
                            HallRowID = 15,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 140,
                            HallRowID = 15,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 141,
                            HallRowID = 15,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 142,
                            HallRowID = 15,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 143,
                            HallRowID = 16,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 144,
                            HallRowID = 16,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 145,
                            HallRowID = 16,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 146,
                            HallRowID = 16,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 147,
                            HallRowID = 16,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 148,
                            HallRowID = 16,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 149,
                            HallRowID = 16,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 150,
                            HallRowID = 16,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 151,
                            HallRowID = 16,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 152,
                            HallRowID = 16,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 153,
                            HallRowID = 17,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 154,
                            HallRowID = 17,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 155,
                            HallRowID = 17,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 156,
                            HallRowID = 17,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 157,
                            HallRowID = 17,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 158,
                            HallRowID = 17,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 159,
                            HallRowID = 17,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 160,
                            HallRowID = 17,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 161,
                            HallRowID = 17,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 162,
                            HallRowID = 18,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 163,
                            HallRowID = 18,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 164,
                            HallRowID = 18,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 165,
                            HallRowID = 18,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 166,
                            HallRowID = 18,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 167,
                            HallRowID = 18,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 168,
                            HallRowID = 18,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 169,
                            HallRowID = 18,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 170,
                            HallRowID = 18,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 171,
                            HallRowID = 18,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 172,
                            HallRowID = 19,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 173,
                            HallRowID = 19,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 174,
                            HallRowID = 19,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 175,
                            HallRowID = 19,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 176,
                            HallRowID = 19,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 177,
                            HallRowID = 19,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 178,
                            HallRowID = 19,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 179,
                            HallRowID = 19,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 180,
                            HallRowID = 19,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 181,
                            HallRowID = 19,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 182,
                            HallRowID = 20,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 183,
                            HallRowID = 20,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 184,
                            HallRowID = 20,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 185,
                            HallRowID = 20,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 186,
                            HallRowID = 20,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 187,
                            HallRowID = 20,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 188,
                            HallRowID = 20,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 189,
                            HallRowID = 20,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 190,
                            HallRowID = 20,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 191,
                            HallRowID = 21,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 192,
                            HallRowID = 21,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 193,
                            HallRowID = 21,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 194,
                            HallRowID = 21,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 195,
                            HallRowID = 21,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 196,
                            HallRowID = 21,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 197,
                            HallRowID = 21,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 198,
                            HallRowID = 21,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 199,
                            HallRowID = 21,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 200,
                            HallRowID = 21,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 201,
                            HallRowID = 22,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 202,
                            HallRowID = 22,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 203,
                            HallRowID = 22,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 204,
                            HallRowID = 22,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 205,
                            HallRowID = 22,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 206,
                            HallRowID = 22,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 207,
                            HallRowID = 22,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 208,
                            HallRowID = 22,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 209,
                            HallRowID = 22,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 210,
                            HallRowID = 23,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 211,
                            HallRowID = 23,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 212,
                            HallRowID = 23,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 213,
                            HallRowID = 23,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 214,
                            HallRowID = 23,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 215,
                            HallRowID = 23,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 216,
                            HallRowID = 23,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 217,
                            HallRowID = 23,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 218,
                            HallRowID = 23,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 219,
                            HallRowID = 23,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 220,
                            HallRowID = 24,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 221,
                            HallRowID = 24,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 222,
                            HallRowID = 24,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 223,
                            HallRowID = 24,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 224,
                            HallRowID = 24,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 225,
                            HallRowID = 24,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 226,
                            HallRowID = 24,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 227,
                            HallRowID = 24,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 228,
                            HallRowID = 24,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 229,
                            HallRowID = 25,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 230,
                            HallRowID = 25,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 231,
                            HallRowID = 25,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 232,
                            HallRowID = 25,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 233,
                            HallRowID = 25,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 234,
                            HallRowID = 25,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 235,
                            HallRowID = 25,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 236,
                            HallRowID = 25,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 237,
                            HallRowID = 25,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 238,
                            HallRowID = 25,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 239,
                            HallRowID = 26,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 240,
                            HallRowID = 26,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 241,
                            HallRowID = 26,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 242,
                            HallRowID = 26,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 243,
                            HallRowID = 26,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 244,
                            HallRowID = 26,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 245,
                            HallRowID = 26,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 246,
                            HallRowID = 26,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 247,
                            HallRowID = 26,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 248,
                            HallRowID = 26,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 249,
                            HallRowID = 27,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 250,
                            HallRowID = 27,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 251,
                            HallRowID = 27,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 252,
                            HallRowID = 27,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 253,
                            HallRowID = 27,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 254,
                            HallRowID = 27,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 255,
                            HallRowID = 27,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 256,
                            HallRowID = 27,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 257,
                            HallRowID = 27,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 258,
                            HallRowID = 27,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 259,
                            HallRowID = 28,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 260,
                            HallRowID = 28,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 261,
                            HallRowID = 28,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 262,
                            HallRowID = 28,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 263,
                            HallRowID = 28,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 264,
                            HallRowID = 28,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 265,
                            HallRowID = 28,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 266,
                            HallRowID = 28,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 267,
                            HallRowID = 28,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 268,
                            HallRowID = 28,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 269,
                            HallRowID = 29,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 270,
                            HallRowID = 29,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 271,
                            HallRowID = 29,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 272,
                            HallRowID = 29,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 273,
                            HallRowID = 29,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 274,
                            HallRowID = 29,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 275,
                            HallRowID = 29,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 276,
                            HallRowID = 29,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 277,
                            HallRowID = 29,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 278,
                            HallRowID = 29,
                            SeatNumber = 10
                        },
                        new
                        {
                            ID = 279,
                            HallRowID = 30,
                            SeatNumber = 1
                        },
                        new
                        {
                            ID = 280,
                            HallRowID = 30,
                            SeatNumber = 2
                        },
                        new
                        {
                            ID = 281,
                            HallRowID = 30,
                            SeatNumber = 3
                        },
                        new
                        {
                            ID = 282,
                            HallRowID = 30,
                            SeatNumber = 4
                        },
                        new
                        {
                            ID = 283,
                            HallRowID = 30,
                            SeatNumber = 5
                        },
                        new
                        {
                            ID = 284,
                            HallRowID = 30,
                            SeatNumber = 6
                        },
                        new
                        {
                            ID = 285,
                            HallRowID = 30,
                            SeatNumber = 7
                        },
                        new
                        {
                            ID = 286,
                            HallRowID = 30,
                            SeatNumber = 8
                        },
                        new
                        {
                            ID = 287,
                            HallRowID = 30,
                            SeatNumber = 9
                        },
                        new
                        {
                            ID = 288,
                            HallRowID = 30,
                            SeatNumber = 10
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Personal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Personal");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "Дмитрий",
                            LastName = "Широков",
                            Login = "admin",
                            MiddleName = "Романович",
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            PhoneNumber = "+79513538360",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Зинаида",
                            LastName = "Ромашкова",
                            Login = "cashier1",
                            MiddleName = "Григорьевна",
                            Password = "5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5",
                            PhoneNumber = "+79229334455",
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BookingID")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BookingID");

                    b.HasIndex("TicketID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PersonalRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PersonalRole = "admin"
                        },
                        new
                        {
                            ID = 2,
                            PersonalRole = "cashier"
                        });
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Seance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CinemaHallHallNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("FilmID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SeanceDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CinemaHallHallNumber");

                    b.HasIndex("FilmID");

                    b.ToTable("Seance");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("PersonalID")
                        .HasColumnType("integer");

                    b.Property<int?>("RowID")
                        .HasColumnType("integer");

                    b.Property<int>("SeanceID")
                        .HasColumnType("integer");

                    b.Property<int?>("SeatID")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("PersonalID");

                    b.HasIndex("RowID");

                    b.HasIndex("SeanceID");

                    b.HasIndex("SeatID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Time", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("SeanceTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("Time");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            SeanceTime = new DateTime(1, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            SeanceTime = new DateTime(1, 1, 1, 11, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            SeanceTime = new DateTime(1, 1, 1, 13, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            SeanceTime = new DateTime(1, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            SeanceTime = new DateTime(1, 1, 1, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            SeanceTime = new DateTime(1, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            SeanceTime = new DateTime(1, 1, 1, 23, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            SeanceTime = new DateTime(1, 1, 1, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            SeanceTime = new DateTime(1, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            SeanceTime = new DateTime(1, 1, 1, 13, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            SeanceTime = new DateTime(1, 1, 1, 16, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            SeanceTime = new DateTime(1, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            SeanceTime = new DateTime(1, 1, 1, 21, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            SeanceTime = new DateTime(1, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            SeanceTime = new DateTime(1, 1, 1, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            SeanceTime = new DateTime(1, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            SeanceTime = new DateTime(1, 1, 1, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            SeanceTime = new DateTime(1, 1, 1, 23, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            SeanceTime = new DateTime(1, 1, 1, 9, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            SeanceTime = new DateTime(1, 1, 1, 11, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            SeanceTime = new DateTime(1, 1, 1, 13, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            SeanceTime = new DateTime(1, 1, 1, 21, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            SeanceTime = new DateTime(1, 1, 1, 8, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            SeanceTime = new DateTime(1, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            SeanceTime = new DateTime(1, 1, 1, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            SeanceTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            SeanceTime = new DateTime(1, 1, 1, 17, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            SeanceTime = new DateTime(1, 1, 1, 19, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            SeanceTime = new DateTime(1, 1, 1, 22, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FilmGenre", b =>
                {
                    b.Property<int>("FilmsID")
                        .HasColumnType("integer");

                    b.Property<int>("GenreID")
                        .HasColumnType("integer");

                    b.HasKey("FilmsID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("FilmGenre");
                });

            modelBuilder.Entity("HallSeatSeance", b =>
                {
                    b.Property<int>("BoughtSeancesID")
                        .HasColumnType("integer");

                    b.Property<int>("BoughtSeatsID")
                        .HasColumnType("integer");

                    b.HasKey("BoughtSeancesID", "BoughtSeatsID");

                    b.HasIndex("BoughtSeatsID");

                    b.ToTable("SeanceBoughtSeats");
                });

            modelBuilder.Entity("HallSeatSeance1", b =>
                {
                    b.Property<int>("ReservedSeancesID")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedSeatsID")
                        .HasColumnType("integer");

                    b.HasKey("ReservedSeancesID", "ReservedSeatsID");

                    b.HasIndex("ReservedSeatsID");

                    b.ToTable("SeanceReservedSeats");
                });

            modelBuilder.Entity("CinemaHallTime", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.CinemaHall", null)
                        .WithMany()
                        .HasForeignKey("HallsHallNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaLibrary.Entity.Time", null)
                        .WithMany()
                        .HasForeignKey("SeanceTimesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Booking", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.HallRow", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.CinemaHall", "CinemaHall")
                        .WithMany("Rows")
                        .HasForeignKey("CinemaHallID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaHall");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.HallSeat", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.HallRow", "HallRow")
                        .WithMany("Seats")
                        .HasForeignKey("HallRowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallRow");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Personal", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Role", "Role")
                        .WithMany("Personals")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Reservation", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Booking", null)
                        .WithMany("Reservations")
                        .HasForeignKey("BookingID");

                    b.HasOne("CinemaLibrary.Entity.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Seance", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.CinemaHall", "CinemaHall")
                        .WithMany()
                        .HasForeignKey("CinemaHallHallNumber");

                    b.HasOne("CinemaLibrary.Entity.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmID");

                    b.Navigation("CinemaHall");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Ticket", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalID");

                    b.HasOne("CinemaLibrary.Entity.HallRow", "Row")
                        .WithMany()
                        .HasForeignKey("RowID");

                    b.HasOne("CinemaLibrary.Entity.Seance", "Seance")
                        .WithMany()
                        .HasForeignKey("SeanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaLibrary.Entity.HallSeat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatID");

                    b.Navigation("Personal");

                    b.Navigation("Row");

                    b.Navigation("Seance");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("FilmGenre", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaLibrary.Entity.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HallSeatSeance", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Seance", null)
                        .WithMany()
                        .HasForeignKey("BoughtSeancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaLibrary.Entity.HallSeat", null)
                        .WithMany()
                        .HasForeignKey("BoughtSeatsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HallSeatSeance1", b =>
                {
                    b.HasOne("CinemaLibrary.Entity.Seance", null)
                        .WithMany()
                        .HasForeignKey("ReservedSeancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaLibrary.Entity.HallSeat", null)
                        .WithMany()
                        .HasForeignKey("ReservedSeatsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Booking", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.CinemaHall", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.HallRow", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("CinemaLibrary.Entity.Role", b =>
                {
                    b.Navigation("Personals");
                });
#pragma warning restore 612, 618
        }
    }
}
